### ISSUE TITLE
MDN layout issue: tables too wide when viewport is 769px and 1200px

### ISSUE THREAD

**Issue by estelle** [mdn/yari#10346]
In the CSS, there is the line:

```css
@media screen and (min-width: 769px) {
  .table-container {
    width: calc(100% + 6rem);
  }
}
```
with the table being 100% of the container, the table is 6em wider than the paragraphs above and below. The alignment looks off on the left, but it looks actually cut off on the right. 

partial screen grab of a page with this issue attached:

<img width="879" alt="Screenshot: table juts to the left of the text by 3em on the left and looks like it is cut off on the right" src="https://github.com/mdn/content/assets/69888/8e48e4e2-0efc-42ef-818c-65253719d349">

Example taken from: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Values_and_units
