### ISSUE TITLE
Clean up mdn.mozillademos.org file URLs

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#1190]
https://github.com/mdn/yari/pull/1188 will take care of converting most of the `<img src="https://mdn.mozillademos.org/files/**/*.png">` tags from the content. 
But there are many other mentions URLs like that that aren't in `<img src>` tags. For example, on http://localhost:3000/en-US/docs/Web/CSS/CSS_Background_and_Borders/Box-shadow_generator there's CSS sample code that looks like this:

```css
.ui-checkbox &gt; input:checked + label {
	background-image: url("https://mdn.mozillademos.org/files/5681/checked.png");
	background-color: #379B4A;
}
```
