### ISSUE TITLE
Cache the root node_modules only

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#210]
At the moment our [travis.yml caching definition](https://github.com/mdn/stumptown-renderer/blob/279f93a9d8ddb82aa1e3252046f354b5bae9c61e/.travis.yml#L11-L14) looks like this:

```yaml
cache:
  yarn: true
  directories:
    - client/node_modules
    - server/node_modules
    - cli/node_modules
```
But now that we're using workspaces, doesn't it put all node modules in 1 single directory in the root?
