### ISSUE TITLE
Content overflow for `flex` description demo

### ISSUE THREAD

**Issue by tannerdolby** [mdn/yari#3589]
## Steps to reproduce
On the [flex](https://developer.mozilla.org/en-US/docs/Web/CSS/flex) page, navigate to the [Description](https://developer.mozilla.org/en-US/docs/Web/CSS/flex#description) section and notice the HTML demo overflows out the right side of the viewport. The content is scrollable so it is viewable, I just wasn't sure if it was supposed to be overflowing or not.

<img width="561" alt="Screen Shot 2021-04-21 at 6 09 09 PM" src="https://user-images.githubusercontent.com/48612525/115640834-b47c3880-a2cc-11eb-9516-d338776362b0.png">

**Comment by peterbe** [comment]
@schalkneethling ?

**Comment by schalkneethling** [comment]
Hey @tannerdolby,

So that is an `iframe` with a width of `1200px` set on it. I had a look and we have this piece of CSS

```css
.main-page-content iframe:not(.sample-code-frame) {
  border: 0;
}
```

if we update that to the following:

```css
.main-page-content iframe:not(.sample-code-frame) {
  border: 0;
  max-width: 100%;
}
```

It fixes the layout problem. The question is, is there an `iframe` somewhere else where this might cause problems. I don’t think so, but maybe?

This also uses a unique class I have not seen before, `example-outcome-frame`

searching over the content I found 8 files that use this class. Of those, 3 sets the width to this `1200px`. The others all use `100%`. As such, I am thinking we should just fix it in the content. I tested it, and all of them will display correctly with the width set to `100%`.

What do you think? @peterbe thoughts?
