### ISSUE TITLE
Browser icons in BC tables have slight vertical misalignment with corresponding text

### ISSUE THREAD

**Issue by tannerdolby** [mdn/yari#4016]
The `<span class="bc-head-txt-label bc-head-icon-edge">Edge</span>` elements have a `::before` pseudo class that creates a `background-image` with each browser icon and absolutely positions it 

```css
.bc-browsers .bc-head-icon-edge:before, .bc-browsers .bc-head-icon-edge_mobile:before {
    background-image: url(/static/media/edge.40018f6a.svg);
}
...
.bc-browsers .bc-head-txt-label:before {
    background-repeat: no-repeat;
    content: "";
    display: inline-block;
    left: -28px;
    position: absolute;
    transform: rotate(
90deg
);
}
```

The icons look super clean and overall really nice, but I noticed they were slightly vertically misaligned. I'm nitpicking here but it is slightly noticeable maybe 1-2px off center where the left side seems bit "off to the left" and not vertically aligned with the text above it.

<img width="940" alt="off-center" src="https://user-images.githubusercontent.com/48612525/121844616-189df600-cc99-11eb-93e2-860e7fe8de6d.png">

Since the pseudo element is absolutely positioned and already has `left: 27px`, we can just move it over a few pixels using `top: 1.5px` to better align it with the text above, we use `top` since the element is being rotated 90deg. Although this is just a cosmetic fix, I think that it does bring some value. Here is the alignment after adding `top: 1.5px` to the pseudo element with browser icon background image.

<img width="953" alt="center" src="https://user-images.githubusercontent.com/48612525/121845139-da550680-cc99-11eb-92d5-7393ea17faa8.png">

I can see a noticeable improvement in alignment where its now "almost" perfectly vertically aligned with the text above it. Let me know what you think @schalkneethling !
