### ISSUE TITLE
Replace all @import with @use rules in scss files

### ISSUE THREAD

**Issue by tannerdolby** [mdn/yari#4242]
> The Sass team discourages the continued use of the @import rule. Sass will gradually phase it out over the next few years, and eventually remove it from the language entirely. Prefer the @use rule instead. (Note that only Dart Sass currently supports @use. Users of other implementations must use the @import rule instead.) [@import](https://sass-lang.com/documentation/at-rules/import)

I'm pretty sure Yari & `mdn/minimalist` are using [dart-sass](https://sass-lang.com/dart-sass) the primary implementation of Sass. Thus, replacing all `@import` rules with `@use` could definitely start happening as a "tidying" task.

**Comment by peterbe** [comment]
Yes, we're using the Dart implementation. 

Is it as simple as:

```diff
-@import "~@mdn/minimalist/sass/mdn-minimalist";
+@use "~@mdn/minimalist/sass/mdn-minimalist";
```
and then `dart-sass` is happier?

**Comment by tannerdolby** [comment]
> Is it as simple as: `@import "url"` -> `@use "url"` and then `dart-sass` is happier?

Correct!

**Comment by tannerdolby** [comment]
There are 123 `@import` rules scattered throughout Yari

<img width="296" alt="Screen Shot 2021-07-19 at 2 08 11 PM" src="https://user-images.githubusercontent.com/48612525/126227736-b8d25e3b-0e37-4a3e-81b0-a61125a548c9.png">

I'm happy to do a mass-replace to change each `@import` to a `@use` rule.

**Comment by peterbe** [comment]
> There are 123 `@import` rules scattered throughout Yari
> 
> <img alt="Screen Shot 2021-07-19 at 2 08 11 PM" width="296" src="https://user-images.githubusercontent.com/48612525/126227736-b8d25e3b-0e37-4a3e-81b0-a61125a548c9.png">
> 
> I'm happy to do a mass-replace to change each `@import` to a `@use` rule.

Perhaps sit on a little. Everyone makes a mental note to fix it in whenever touching any page that has the old syntax. Eventually, there'll only be a few stragglers left. 
This might make reviewing safer and saner.

**Comment by tannerdolby** [comment]
cc @schalkneethling

**Comment by schalkneethling** [comment]
> cc @schalkneethling

:) I am in the process of doing that with the redesign. Thanks for the ping @tannerdolby - Also, I have already switched most of minimalist to use `@use`

**Comment by tannerdolby** [comment]
> :) I am in the process of doing that with the redesign. Thanks for the ping @tannerdolby - Also, I have already switched most of minimalist to use @lfirek 

Ok excellent! :) Your welcome @schalkneethling - Cool, I will close the issue I opened in minimalist regarding replacing `@import` rules with `@use`.

**Comment by tannerdolby** [comment]
As an update, I converted all the `@import` rules in `mdn/minimalist` (aside from 4 remaining import rules used for the test suite, which is partly an issue with `sass-true`)

The overhaul in minimalist wasn't all that much work. The one thing to remember is that `@import` rules don't create a namespace when imported modules/stylesheets, where `@use` rules do introduce a namespace associated with the imported module. To avoid having to change any of the original mixins and variable usage in `mdn/minimalist`, I just imported the modules with `@use` rules without a namespace defined like this `@use "url" as *` where `as *` is the alias the module will be referenced as. [@use - choosing a namespace](https://sass-lang.com/documentation/at-rules/use#choosing-a-namespace)

So here in `mdn/yari`, we would be doing the same conversion as in `mdn/minimalist`. Replace any `@import` rules that are bringing in stylesheets with mixins/variables with the `@use "foo" as *` so the module isn't scoped to a specific namespace when we try and reference the variables and mixins stored within. If the stylesheet being imported only contains css (no mixins or variables) then the switch from `@import` to `@use` is as simple as:

```scss
@import "./dir/some-url";  ---> @use "./dir/some-url";
```

Where if the module contained mixins/variables then we would do this, so the stylesheets wouldn't have to undergo any changes outside of the `@import` rules being replaced with `@use`

```scss
// some module that contains mixins

@import "./dir/my-mixins";  ---> @use "./dir/my-mixins" as *;
@import "./dir/my-vars"; ---> @use "./dir/my-vars" as *;

.foo {
 @include some-mixin();
color: $mdn-neutral400;
}
```

If we didn't make it so the modules don't have a defined namespace with `as *` then the namespace would be the last component of its URL without the file extension like this

```scss
// some module that contains mixins

@import "./dir/mixins";  ---> @use "./dir/my-mixins";
@import "./dir/vars"; ---> @use "./dir/my-vars";

.foo {
 @include mixins.some-mixin();
color: vars.$mdn-neutral400;
}

// or with a specific namespace 
// some module that contains mixins

@import "./dir/my-mixins";  ---> @use "./dir/my-mixins" as m;
@import "./dir/my-vars"; ---> @use "./dir/my-vars" as v;

.foo {
 @include m.some-mixin();
color: v.$mdn-neutral400;
}
```

To avoid having to change any of the cool scss stuff in stylesheets (ie mixin usage and variable usage) we just opt to not define a namespace for imported modules with mixins and variables. As I overhauled the `@import` rules to `@use` in minimalist, I'm confident we can make a smooth transition here in Yari too, for the styles that aren't directly coming from `mdn/minimalist`.
