### ISSUE TITLE
Issue with "Array": (text overlap with Object.prototype.propertyIsEnumerable() link at 110% zoom on chrome )

### ISSUE THREAD

**Issue by dnlbellfield** [mdn/yari#4326]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array

#### What information was incorrect, unhelpful, or incomplete?
On this page: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array
there is a link on the side of the page, Object.prototype.propertyIsEnumerable() , that overlaps 'Accessing array elements' title.  

#### Specific section or headline?
Object.prototype.propertyIsEnumerable() link's text, 
overlaps the Accessing array elements 'title' 
when the zoom is at 110% zoom on chrome. The text almost overlaps at 100%
#### Did you test this? If so, how?
I set my chrome browsers zoom to 110% and noticed a link overlapping a title. 

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/array`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/array/index.md
* Last commit: https://github.com/mdn/content/commit/cf607d68522cd35ee7670782d3ee3a361eaef2e4
* Document last modified: 2021-07-20T18:47:57.000Z

</details>

**Comment by peterbe** [comment]
@dnlbellfield What browser is that?

CC @tannerdolby

**Comment by tannerdolby** [comment]
> Instead of going for word-wrap property. I think this (...) is much better.

Using `text-overflow: ellipsis` is a "design smell" and accessibility concern so that will not be an option here. I also don't like the concept of having sidebar content (which is already quite small in width usually 20-40ch) be scrollable, so using `overflow: auto` also doesn't seem to be the "right" fix.

The `word-break` usage is fine and makes the most sense paired with `white-space`. The root of the problem is `white-space: nowrap` on the nested `<code>` elements within `<a>` tags in the sidebar, which is forcing the elements not to have white space collapsed and not allowing text wrapping to the next line. In `_code.scss` the following styles are applied:

```scss
// _code.scss
code {
    -webkit-box-decoration-break: clone;
    box-decoration-break: clone;
    font-family: consolas,"Liberation Mono",courier,monospace;
    padding: 0 3px;
    white-space: nowrap; /* Causing the text to overflow into the <main> content around 1320px */
    word-wrap: break-word;
}
```

As we want to stay away from any `ellipsis` styling for overflowed content, the fix here is most likely going to be simply updating `white-space` on those code tags, having the text wrap onto to the next line by changing `white-space` to `normal` or `break-spaces`. Since the `_code.scss` style block for `code {}` probably selects/applies to other `<code>` elements, I think updating white-space from the `.sidebar code` selector will probably be best (unless changing the `code {}` selector in _code.scss is fine and doesn't affect any other parts of the page).
