### ISSUE TITLE
Make tables in main page content scrollable at narrow viewport widths (mobile)

### ISSUE THREAD

**Issue by simevidas** [mdn/yari#5142]
The data tables in MDN’s content are not responsive. When viewing an MDN page with tables on a mobile phone, the entire page scrolls in the horizontal direction (see the image below). 

One way to avoid this would be to put the tables in `<div>` scroll containers.

```html
<div role="region" aria-labelledby="Caption01" tabindex="0">
  <table>[…]</table>
</div>
```

```css
[role="region"][aria-labelledby][tabindex] {
  overflow: auto;
}

[role="region"][aria-labelledby][tabindex]:focus {
  outline: .1em solid rgba(0,0,0,.1);
}
```

Source for code: https://twitter.com/aardrian/status/1326150127959105538

![cafbc98c2833128761911162e233c903--retina-mockup](https://user-images.githubusercontent.com/716405/148620426-677de0a7-b0f9-4ed7-b54f-e6ff98efe473.jpg)
