### ISSUE TITLE
Dark mode a little too contrasty

### ISSUE THREAD

**Issue by saltire** [mdn/yari#5378]
# Summary

Thanks for the new dark mode option! 🖤 My only feedback is that it might be a bit *too* dark: so much contrast with the white text can make it hard to read. I have slight astigmatism, so it might be that; I've heard it's a common problem.

I gave the same feedback to GitHub when they released their dark mode; they later released a "dim" mode with a slightly lighter background, and it helped a lot. The TypeScript docs site is another good example of an easier contrast, and so is the dark mode on MacOS.

Other than this I'm jazzed for the redesign, and happy to see great work go into a site I use and learn from every day. Cheers!

**Comment by mayank99** [comment]
I agree with this.

In the meantime, I am creating my own "dimmed dark" mode by adding this custom rule on my end (using the Stylus extension).
```css
:root, .dark {
    --background-primary: hsl(250 15% 20%);
    background: var(--background-primary) !important;
}
```

That second line is only needed if you've already changed your theme once (see #5380).
