### ISSUE TITLE
Whitespace, Header styling, code background contrast, remove 3rd column, etc

### ISSUE THREAD

**Issue by e3dio** [mdn/yari#5389]
I'm adding CSS styles here for people who need to use this site for work and get things done: less whitespace, better headers, full screen width, sidebar element spacing, code background contrast, scrollbar styling, always open search input, sticky top headers, darker dark mode, and other misc. updates: use extension like [Stylus](https://chrome.google.com/webstore/detail/stylus/clngdbkpkpeebahjckkjfobafhncgmne?hl=en) to add styles

<details>
  <summary>Click to expand CSS styles</summary>

```css
h1, h2, h3, h4 {
    margin: .75rem 0 !important;
}
h1, h2 {
    font-weight: bold;
}
h2 {
    font-size: 1.6rem;
}
h3 {
    font-size: 1.25rem;
    font-weight: 600;
    margin-left: 1rem !important;
}
p {
    padding-left: 1rem;
    line-height: 150% !important;
    margin: .75rem 0 !important;
}
a {
    padding: 0 !important;
}
a > code { 
    color: var(--text-link);
}
pre {
    padding: 0.45rem 0.7rem;
    margin: 0.75rem 0.5rem 0.5rem 1rem;
}
code {
    background: hsl(240deg 10% 95%);
}
pre {
    background: hsl(240deg 10% 96%);
}
.dark code {
    background: hsl(247deg 10% 20%);
}
.dark pre {
    background: hsl(247deg 10% 10%);
}
pre code {
    background: none !important;
}
body #sidebar-quicklinks code {
    background: none;
}
body.dark {
    background: #000 !important;
}
#content {
    padding: 0 .5rem 0 .75rem;
    box-shadow: -5px 0 5px -5px #888;
    overflow-x: hidden;
}
.logo svg {
   margin-top: 0;
}
.article-wrapper .main-content, .article-wrapper .sidebar, .article-wrapper .toc{
    padding-top: 0;
    padding-bottom: 0;
}
.article-wrapper {
    padding-left: 0.5rem;
    padding-right: 0rem;
}
.article-wrapper {
    gap: 0rem;
}
.article-actions-container {
    position: sticky;
    top: 33px;
    z-index: 99;
}
.dark .article-actions-container {
    background: #000000;
}
.top-navigation {
    position: sticky;
    top: 0;
}
.dark .top-navigation {
    background: #000000;
}
#sidebar-quicklinks {
    top: 65px;
    max-height: calc(100vh - 65px);
    overflow-x: hidden;
}
.main-page-content dl dt {
    margin-top: .5rem;
}
.sidebar li, .sidebar summary {
    margin-bottom: 0rem;
}
.sidebar li strong {
    margin: 0.5rem 0;
}
.sidebar li details {
    margin: 0;
}
.sidebar details ol {
    margin: 0.25rem 0.5rem;
    padding-left: 0.75rem;
}
.article-wrapper {
     max-width: unset;
}
.document-toc-list.document-toc-list li {
    margin: 2px 0;
}
.document-toc {
    margin-bottom: 0rem;
}
.document-toc-link.document-toc-link:not(.button) {
    padding: 0 0 0 .5rem !important;
}
.toc {
    display: none !important;
}
.main-page-content ol li, .main-page-content ul li {
    margin: 0.25rem 0;
    line-height: 150%;
}
.main-page-content ol, .main-page-content ul {
    margin: 0.5rem 0 0.5rem;
}
.main-page-content dl dt {
    margin-left: 1rem;
    margin-top: 0.5rem;
}
.main-page-content a:link, .main-page-content a:visited {
    text-decoration: none;
}
.main-page-content a:hover {
    text-decoration: underline;
}
.container {
    max-width: 100%;
}
.callout {
    padding: 0rem;
    gap: 0;
    margin: 1rem 0;
    text-align: center;
}
.breadcrumb:hover span, .breadcrumb-current-page:hover span {
    text-decoration: underline;
}
.close-search-button {
    display: none;
}
.search-button {
    display: none;
}
.top-navigation-main .header-search {
    max-width: 280px;
}
#top-nav-search-q {
    height: 28px;
    padding: 0 10px;
    margin: 2px 0px;
}
.switch .slider {
    background-color: var(--text-link);
}
.dark .switch .slider {
    background-color: var(--text-secondary) !important;
}
.mdn-cta-container, .auth-container {
    display: none;
}
@media screen and (min-width: 769px) {
    .article-wrapper {
        grid-template-columns: min(250px, 20%) 1fr;
    }
    .breadcrumbs-container li {
        display: inline-flex !important;
    }
    .top-navigation-main .search-form {
        display: block;
    }
    .top-navigation-main .toggle-search-button {
        display: none;
    }
}
@media screen and (min-width: 1200px) {
    .article-wrapper {
        grid-template-columns: min(250px, 20%) 1fr;
        grid-template-areas: "sidebar main";
    }
    .article-wrapper .in-nav-toc {
        display: block;
    }
}
:root {
    --top-nav-height: 1rem;
}
:target {
    scroll-margin-top: 70px;
}
::-webkit-scrollbar {
    width: 10px;
    height: 6px;
}
body ::-webkit-scrollbar-thumb {
    background: #ccc;
}
body ::-webkit-scrollbar-track {
    background: #eee;
}
.dark ::-webkit-scrollbar-track {
    background: hsl(0deg 0% 5%);
}
.dark ::-webkit-scrollbar-thumb {
    background: hsl(0deg 0% 15%);
}
```

</details>

# Before:

![image](https://user-images.githubusercontent.com/85405955/157786692-14a89b42-a763-4d81-9a23-bf6dbc2a17d6.png)

# After:

![image](https://user-images.githubusercontent.com/85405955/157786299-7963ff87-9085-466d-910e-27e0489b7fba.png)

# Before:

![image](https://user-images.githubusercontent.com/85405955/157516608-85ba3f25-6efd-4b7f-9a8f-9a7559bbf0b0.png)

# After:

![image](https://user-images.githubusercontent.com/85405955/157786263-4e4519d5-496f-42ed-a90e-397ae6525505.png)

**Comment by saleh5yu** [comment]
***@***.***

في الثلاثاء، ١ مارس ٢٠٢٢ ٢٣:٤٨ e3dio ***@***.***> كتب:

**Comment by saleh5yu** [comment]
***@***.***

في الثلاثاء، ١ مارس ٢٠٢٢ ٢٣:٤٩ صالح صالح ***@***.***> كتب:

**Comment by DCzajkowski** [comment]
@e3dio thank you for your service 🙌

**Comment by e3dio** [comment]
> After the redesign, we noticed that our new theme switch does not follow the [general consensus](https://duckduckgo.com/?q=material+design+switch&iax=images&ia=images) of how the off state should look.

Turning "on" the lights means the switch is in the on position. Turning "on" the dark makes less sense. Thanks for closing off discussion for people who use your site, real mature

**Comment by caugner** [comment]
Hi @e3dio, we appreciate your effort and would like to adopt some of the style changes that you're suggesting. 👍 

For this to happen, however, we would require additional documentation for each change as to what problem it addresses and how it is solved.

If that sounds good to you, please write this documentation as if you would explain the problem and solution to a user who knows HTML and typography basics, but not CSS. This avoids repeating what the styles already say.

**Note**:
- You might have to split blocks, if they're addressing multiple issues altogether.
- You can use one comment for multiple blocks, if they address the same problem with the same solution.
- Please don't create any new issues, even if no issue exists yet for a problem that you're addressing.

Example:

```
/*
  Problem: h2 headings are hard to distinguish from h3 headings.
  Solution: Make h2 headings bolder.
  Issues: #5485
  PRs: #5442
*/
h2 {
    font-weight: bold;
}
```

Thanks!

**Comment by caugner** [comment]
> Turning "on" the lights means the switch is in the on position. Turning "on" the dark makes less sense.

Feel free to open a PR that replaces our switch by a theme switch like the one used by Vue.js: https://vuejs.org/

**Comment by OnkarRuikar** [comment]
We can have search box above Table of Contents(TOC)  and only breadcrumbs sticky. 
![img](https://i.imgur.com/QRfhtzS.png)

**Comment by pmario** [comment]
I did test the "breadcrumb container" with `position: sticky;`, which is **almost ok** see: 

The **Validation** heading is hidden behind the container

![grafik](https://user-images.githubusercontent.com/374655/157890959-82984911-1733-4426-b4d8-e134a9fba214.png)

**expected is **

![grafik](https://user-images.githubusercontent.com/374655/157891231-5a5febf1-df15-4877-ab1d-5b86e687c921.png)

**Comment by e3dio** [comment]
There is special CSS trick to fix that for sticky headers, check my CSS for rule:
```css
:target {
    scroll-margin-top: 70px;
}
```
This depends on the height of the combined headers which in my CSS includes the main header and is shorter than normal
