### ISSUE TITLE
Bug: Links are not clearly differentiated

### ISSUE THREAD

**Issue by joelanman** [mdn/yari#5445]
# Summary

Links are not clearly differentiated from other elements (headings, body text). Sometimes they look identical to other elements (headings) sometimes they have a colour variation.

Sometimes links are obvious from their context (say a browse menu) but otherwise the most accessible way to differentiate links from surrounding elements is to use an underline.

**Comment by caugner** [comment]
Hi @joelanman, thank you for taking the time to report this issue. 👋 

Would you be able to add some URLs and a screenshot to illustrate the issue you're reporting? That would be great. 🙂

**Comment by joelanman** [comment]
its a problem on nearly every page, but as an example:

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input

some links are black, some are red, some are grey, none are underlined as far as I can tell. It's just really unclear what are links and what is just text

**Comment by davidluhr** [comment]
Some of the link text within a nested `<code>` element is rendering with `--text-secondary` (light gray) because of a direct descendant selector:

```css
a > code {
  color: var(--code-color);
}
```

This selector doesn't apply to many of the links in `<dl>`/`<dt>`/ `<dd>` content due to the HTML structure:

```html
<a id="attr-checked" href="#attr-checked">
  <b>
    <code>checked</code>
  </b>
</a>
```

The `<b>` element doesn't have any effect, so it could be removed. Alternatively, the CSS selector code simply be `a code { ... }` instead of `a > code { ... }` to select more than direct descendants.

In addition to this, I found anchor link text within a nested `<code>` element does not provide an underline on hover due to overriding specificity.

This hover style loses:
```css
.main-page-content a:not(.button):focus, .main-page-content a:not(.button):hover {
  text-decoration: underline;
}
```

to this selector:
```css
.main-page-content a:not(.button)[aria-current] {
  text-decoration: none;
}
```
