### ISSUE TITLE
TOC : When TOC gets in sidebar `<em>` elements get unwanted highlight

### ISSUE THREAD

**Issue by OnkarRuikar** [mdn/yari#6037]
### Summary

On less than 769px wide viewport the TOC is placed inside left-hand sidebar. And in such case `<em>` elements are getting highlighted.

### URL

https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/React_components#tasks_as_data

### Reproduction steps

1. Reduce viewport width so that TOC gets inside sidebar.
2. Notice the word "_unique_" gets highlighted in TOC.

### Expected behavior

Highlight only current list items.

### Actual behavior

![bug](https://i.imgur.com/h2Wl3CL.png)

I think this is happening because of following CSS rule:
```css
.sidebar em {
  background-color: var(--background-toc-active);
  border-left: 2px solid var(--category-color);
  display: inline-block;
  width: 100%;
}
```
I think we need to remove text decorations from TOC.

### Device

Desktop

### Browser

Chrome

### Browser version

Stable

### Operating system

Windows

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).
