### ISSUE TITLE
Stylelint: fix current issues and prevent future issues

### ISSUE THREAD

**Issue by caugner** [mdn/yari#6455]
# Problem

We have stylelint in our repository, but we don't run it systematically, so we currently have 1000+ errors:

```
% yarn stylelint -q '**/*.scss' | grep '✖' | wc -l
error Command failed with exit code 2.                                                                                                                                                                   
    1302
```

# Solution

1. Verify whether the rules causing errors make sense.
2. Fix the current errors automatically (and - in a separate commit - manually if necessary).
3. Run `stylelint` as part of `lint-staged`, to avoid introducing new errors.
4. Run `stylelint` as part of the `.github/workflows/testing.yml` workflow.

**Bonus**: Integrate `stylelint` with ESLint (to avoid having to run it separately).

**Comment by mustaphaturhan** [comment]
This issue amazing for me. I can take it ✌️

**Comment by caugner** [comment]
Awesome, thank you so much! 🙏

**Comment by caugner** [comment]
@mustaphaturhan Maybe

- To fix `declaration-property-value-disallowed-list`, we should be able to replace `border: none` with `border: 0`.
- For your `no-descending-specificity` example, the solution looks good to me.
- To fix the `no-duplicate-selectors` error, we should then be able to merge the two blocks that start with `ul.main-menu` like this:
```scss
@media screen and (min-width: $screen-lg) {
  .open-on-focus-within {
    .submenu,
    .watch-submenu {
      display: none;
    }
  }

  ul.main-menu {
    .submenu {
      display: none;
    }

    .top-level-entry-container {
      &:hover,
      &:focus-within {
        .submenu {
          display: block;
        }
    }
  }

  // This allows keyboard nav to work more predictably on desktop dropdowns.
  .open-on-focus-within {
    &:focus-within {
      .watch-submenu {
        display: flex;
      }

      .submenu {
        display: block;
      }
    }
  }
}
```
