### ISSUE TITLE
Use git log to know a documents last modified date

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#706]
At the time of writing, we're only using the `.modified` date in the sitemaps XML files we build at the end of the builder. But we should really soon have a "last modified" displayed in the footer of every document. 

For documents that have been imported from MySQL we get this from the `wikihistory.json` but not for documents that came into existence *after* the MySQL import.

**Comment by peterbe** [comment]
@Gregoor and I dug into this early in Jan 2020 and we managed to write an "algorithm" that uses `git` libraries that can look up a complete map of `path => date` based on `git log` and since that's fast, we make that map once instead of having to figure it out on one-document-at-a-time basis in the builder. 

What we stumbled on was that `nodegit` wasn't supported in modern versions of Node so the examples we proved were done with Python and Rust.

**Comment by peterbe** [comment]
I'm going to wait for https://github.com/mdn/yari/pull/1510 because I know it has a nifty wrapper on `child_process` called `gitExec` which I'd want to use to control the gathering of the git logs from within Node. 
Also, it might be good idea to just git clone the whole thing with no depth set. I.e. full depth. Setting `fetch-depth: 0` in [actions/checkout](https://github.com/actions/checkout). That's going to work for a very long time.

@fiji-flo Had an interesting idea. We could potentially control that `fetch-depth` parameter to `actions/checkout` by first attempting to retrieve the last log file from the cache. Something like this::

```yaml
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Cache git log JSON
      id: cache-git-log
      uses: actions/cache@v2
      with:
        path: git-log.json
        key: ${{ runner.os }}-git-log.json

    - uses: actions/checkout@v2
      with:
        fetch-depth: ${{ steps.cache-git-log.outputs.cache-hit == 'true' && 100 || 0 }}
    
    - name: Build Yari
       ...

    - name: Dump git-log.json
      run: node cli.js dump-git-log-past -o git-log.json
```
